extends: v5_ad_metadata_walk_forward_100m_s10.yaml

experiment:
  name: two_tower_v6_context_metadata_walk_forward_100m_s10

paths:
  oof_requests_file: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v6_context_metadata_walk_forward_100m_s10/oof_requests.parquet
  history_events_file: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v6_context_metadata_walk_forward_100m_s10/history_events.parquet
  dataset_artifact_dir: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v6_context_metadata_walk_forward_100m_s10
  artifact_dir: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v6_context_metadata_walk_forward_100m_s10
  full_quality_artifact: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v6_context_metadata_chrono_100m_model

tracking:
  underdeep:
    run_name: two-tower-v6-context-metadata-walk-forward-100m-s10

model:
  query_cardinalities:
    device_ids: 1024
    age_bucket_ids: 128
    gender_ids: 8
