extends: v8_logq_chrono100m_valfit_full.yaml

experiment:
  name: two_tower_v8_logq_half_chrono100m_valfit_full

paths:
  base_artifact: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v8_logq_half_chrono_100m_model
  artifact_dir: /home/astrofimuk/workspace/mla_two_stage/artifacts/two_tower_v8_logq_half_chrono100m_valfit_full

tracking:
  underdeep:
    run_name: two-tower-v8-logq-half-chrono100m-valfit-full
